[build]
  command = "react-router build"
  publish = "build/client"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "build/client,build/server"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL,VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL,SUPABASE_ANON_KEY"